# Generated by Django 4.2.11 on 2024-04-06 18:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RE_API', '0002_remove_property_propertyimage_property_rentprice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='contact',
            new_name='contract',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='paymentAmount',
        ),
        migrations.AddField(
            model_name='payment',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RE_API.contract'),
        ),
        migrations.AlterField(
            model_name='request',
            name='issuedOn',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 18, 38, 3, 311375, tzinfo=datetime.timezone.utc)),
        ),
    ]
