# Generated by Django 4.2.11 on 2024-04-07 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RE_API', '0004_alter_contract_depositamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='expiryDate',
            field=models.DateField(default=datetime.datetime(2024, 4, 7, 5, 55, 24, 924126, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.DateField(default=datetime.datetime(2024, 4, 7, 5, 55, 24, 925152, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='request',
            name='issuedOn',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 7, 5, 55, 24, 926152, tzinfo=datetime.timezone.utc)),
        ),
    ]
