# Generated by Django 4.2.11 on 2024-04-07 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RE_API', '0006_contract_renewal_date_contract_renewal_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='renewal_date',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='renewal_option',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='termination_date',
        ),
        migrations.AlterField(
            model_name='contract',
            name='expiryDate',
            field=models.DateField(default=datetime.datetime(2024, 4, 7, 6, 39, 24, 593420, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.DateField(default=datetime.datetime(2024, 4, 7, 6, 39, 24, 594416, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='request',
            name='issuedOn',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 7, 6, 39, 24, 595414, tzinfo=datetime.timezone.utc)),
        ),
    ]
