# Generated by Django 4.2.11 on 2024-04-07 07:00

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RE_API', '0007_remove_contract_renewal_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='saved',
            field=models.ManyToManyField(blank=True, null=True, related_name='saved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contract',
            name='expiryDate',
            field=models.DateField(default=datetime.datetime(2024, 4, 7, 7, 0, 43, 257592, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.DateField(default=datetime.datetime(2024, 4, 7, 7, 0, 43, 259587, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='request',
            name='issuedOn',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 7, 7, 0, 43, 260615, tzinfo=datetime.timezone.utc)),
        ),
    ]
