# Generated by Django 4.2.11 on 2024-04-07 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RE_API', '0008_property_saved_alter_contract_expirydate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/agencies/'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='expiryDate',
            field=models.DateField(default=datetime.datetime(2024, 4, 7, 15, 57, 20, 302498, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.DateField(default=datetime.datetime(2024, 4, 7, 15, 57, 20, 303498, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='request',
            name='issuedOn',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 7, 15, 57, 20, 304539, tzinfo=datetime.timezone.utc)),
        ),
    ]
