# Generated by Django 4.2.11 on 2024-04-26 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RE_API', '0009_agency_image_alter_contract_expirydate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price_id',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='contract',
            name='expiryDate',
            field=models.DateField(default=datetime.datetime(2024, 4, 26, 15, 30, 45, 698267, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.DateField(default=datetime.datetime(2024, 4, 26, 15, 30, 45, 700261, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='request',
            name='issuedOn',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 15, 30, 45, 700261, tzinfo=datetime.timezone.utc)),
        ),
    ]
