# Generated by Django 4.2.11 on 2024-04-26 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RE_API', '0010_property_price_id_alter_contract_expirydate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='expiryDate',
            field=models.DateField(default=datetime.datetime(2024, 4, 26, 15, 33, 4, 210874, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.DateField(default=datetime.datetime(2024, 4, 26, 15, 33, 4, 212868, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='request',
            name='issuedOn',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 15, 33, 4, 213866, tzinfo=datetime.timezone.utc)),
        ),
    ]
